# Generated by Django 3.2.6 on 2021-08-21 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_notebookproduct_smartphone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoteBookProduct',
            new_name='NoteBook',
        ),
    ]
